/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author macpro2
 */
public class EncuestaTbl extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EncuestaTbl.class.getName());

    Connection conn;

    String url = "jdbc:mysql://localhost:3306/encuesta";
    String user = "encuesta_user";
    String password = "encuesta_pass";

    DefaultTableModel tblModel;

    /**
     * Creates new form EncuestaTbl
     */
    public EncuestaTbl() {
        initComponents();

        tblModel = (DefaultTableModel) tblResp.getModel();

        this.doConnect();
        this.doUpdate();

        tblModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                int type = e.getType();

                if (type == TableModelEvent.UPDATE) {
                    System.out.println("Celda actualizada en renglon: " + row + ", columna: " + column);
                    System.out.println("Nuevo valor: " + tblModel.getValueAt(row, column));
                    
                    int id = (int) tblModel.getValueAt(row, 0);
                    String sSO = (String) tblModel.getValueAt(row, 1);
                    String sPrg = (String) tblModel.getValueAt(row, 2);
                    String sDis = (String) tblModel.getValueAt(row, 3);
                    String sAdm = (String) tblModel.getValueAt(row, 4);
                    int iHrs = (int) tblModel.getValueAt(row, 5);
                    
                    String sent = "UPDATE respuestas SET sSisOper='%s', cProgra='%s',cDiseno='%s',cAdmon='%s', iHoras=%d WHERE id=%d";
                    
                    String sentUpd = String.format(sent,sSO,sPrg,sDis,sAdm,iHrs,id);
                    
                    try {
                        Statement stmt = conn.createStatement();
                        stmt.execute(sentUpd);
                        doUpdate();
                    } catch (SQLException sqle){
                        JOptionPane.showMessageDialog(null, "Error en actualizacion: " + sqle.getMessage(), "Encuesta", JOptionPane.ERROR_MESSAGE);
                    }
     
                } else if (type == TableModelEvent.INSERT) {
                    System.out.println("Renglon insertado en: " + row + " para " + e.getLastRow());
                } else if (type == TableModelEvent.DELETE) {
                    System.out.println("Renglones borrados en: " + row + " para " + e.getLastRow());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResp = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sist. Op.", "Prog.", "Diseño", "Admon.", "Horas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResp);

        btnRefresh.setText("Refrescar");
        btnRefresh.setActionCommand("btnRefreshAction");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        this.doUpdate();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EncuestaTbl().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResp;
    // End of variables declaration//GEN-END:variables

    private void doConnect() {
        try {
            this.conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connection to MySQL established successfully!");
            // Perform database operations here
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en conexión con la BD: " + e.getMessage(), "Encuesta", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error connecting to MySQL: " + e.getMessage());
        }
    }

    private void doUpdate() {
        Statement stmt;
        ResultSet rset;
        String sQuery = "SELECT id, sSisOper, cProgra, cDiseno, cAdmon, iHoras FROM respuestas";

        this.tblModel.setNumRows(0);

        try {
            stmt = this.conn.createStatement();
            rset = stmt.executeQuery(sQuery);

            while (rset.next()) {
                Object objArray[] = new Object[6];
                objArray[0] = rset.getInt("id");
                objArray[1] = rset.getString("sSisOper");
                objArray[2] = rset.getString("cProgra");
                objArray[3] = rset.getString("cDiseno");
                objArray[4] = rset.getString("cAdmon");
                objArray[5] = rset.getInt("iHoras");

                this.tblModel.addRow(objArray);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en consulta: " + e.getMessage(), "Encuesta", JOptionPane.ERROR_MESSAGE);
        }
    }

}
